#!/usr/bin/env Rscript


library(d3heatmap)
library(data.table)
library(reshape2)


args <- commandArgs(trailingOnly = TRUE)
if(length(args)<1) {
    stop("Usage: intermine2heatmap input.txt output.html")
}


x=fread(args[1])
setnames(x,c("transcriptid","sra","sample_name","tissue","brenda","fpkm","normalized_counts","raw_counts"))


z=acast(x,transcriptid~tissue,value.var="fpkm")
filename=ifelse(length(args)>=2,args[2],'output.html')

mat=log(z+1)
widget=d3heatmap(mat)
htmlwidgets::saveWidget(widget,file=filename)


